plugins {
    id 'com.android.application'
}

def versionProperties = new Properties()
file('../version.properties').withInputStream { versionProperties.load(it) }
def appVersionCode = versionProperties.getProperty('versionCode').toInteger()
def appVersionName = versionProperties.getProperty('versionName')

android {
    namespace 'com.cfam.app'
    compileSdk 37

    defaultConfig {
        applicationId 'com.cfam.app'
        minSdk 23
        targetSdk 37
        versionCode appVersionCode
        versionName appVersionName
        resValue 'string', 'app_name', "CFAM v${appVersionName}"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}
